{% set name = "LoadsKernel" %}
{% set version = "2024.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/LoadsKernel-{{ version }}.tar.gz
  sha256: 887fe7b72ccd1a2c0eeacee21460bf2ed1dfeef61c6304b227c503a87590089c

build:
  entry_points:
    - loads-kernel=loadskernel.program_flow:command_line_interface
    - model-viewer=modelviewer.view:command_line_interface
    - loads-compare=loadscompare.compare:command_line_interface
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8,<3.11
    - pip
  run:
    - python >=3.8,<3.11
    - panelaero
    - matplotlib-base
    - numpy
    - scipy
    - psutil
    - h5py
    - pytables
    - pyyaml
    - pandas

test:
  imports:
    - loadscompare
    - loadskernel
    - modelviewer
  commands:
    - pip check
    - loads-kernel --help
  requires:
    - pip

outputs:
  - name: loadskernel

  - name: loadskernel-extras
    requirements:
      host:
        - python >=3.8,<3.11
      run:
        - python >=3.8,<3.11
        - mpi4py
        - pyfmi
        - mayavi
        - traits
        - traitsui
        - pyface
        - pytest
        - pytest-cov
        - jupyter
        - jupyter-book ==0.15.1
        - {{ pin_subpackage('loadskernel', exact=True) }}
    test:
      imports:
        - loadskernel

about:
  home: https://github.com/DLR-AE/LoadsKernel
  summary: The Loads Kernel Software allows for the calculation of quasi-steady and dynamic maneuver loads,
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ArneVoss
